[package]
name = "job-queue"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.17"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"


[dependencies.uuid]
version = "1.19.0"
features = [
    "v4",
    "v7",
]
